version: '3'
services:
  app:
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - '80:8080'
    environment:
      - NODE_ENV=production
    restart: always
  app-db:
    volumes: 
      - db-data:/data/db
    restart: always
volumes:
  db-data: