version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
    depends_on:
      - app-db
    networks:
      - backend
  app-db:
    image: mongo:3
    networks:
      - backend
networks:
  backend: